#!/usr/bin/env node

/**
 * Generate version.ts from package.json
 *
 * This script runs before TypeScript compilation to ensure the version
 * constant in the code always matches package.json.
 */

import { writeFileSync, readFileSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const packageJsonPath = join(__dirname, '../package.json');
const versionFilePath = join(__dirname, '../src/version.ts');

// Read package.json
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Get build metadata
const buildTime = new Date().toISOString();
let commitSha = 'unknown';
let isDirty = false;

try {
    commitSha = execSync('git rev-parse --short HEAD', {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore']
    }).trim();

    // Check if working directory is dirty
    const status = execSync('git status --porcelain', {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
    isDirty = status.length > 0;
} catch (err) {
    // Git not available or not a git repo
    console.warn('Warning: Could not determine git commit SHA');
}

// Generate version.ts content
const content = `// Auto-generated by scripts/generate-version.mjs
// DO NOT EDIT MANUALLY - This file is regenerated on every build

/**
 * Package version from package.json
 */
export const VERSION = "${version}";

/**
 * Build timestamp (ISO 8601)
 */
export const BUILD_TIME = "${buildTime}";

/**
 * Git commit SHA (short)
 */
export const COMMIT_SHA = "${commitSha}${isDirty ? '-dirty' : ''}";

/**
 * Full version string with build metadata
 */
export const FULL_VERSION = \`\${VERSION} (\${COMMIT_SHA}, built \${BUILD_TIME})\`;
`;

// Write version.ts
writeFileSync(versionFilePath, content, 'utf8');

console.log(`✓ Generated version.ts: ${version} (${commitSha}${isDirty ? '-dirty' : ''})`);
